const minify = require('html-minifier').minify;
const fs = require('fs');

const input = fs.readFileSync('index.html', 'utf8');

const output = minify(input, {
  removeAttributeQuotes: true,
  collapseWhitespace: true,
  removeComments: true,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  useShortDoctype: true,
  minifyCSS: true,
  minifyJS: true,
  includeAutoGeneratedTags: false
});

// Manual hack to remove final closing tags if they exist
let finalOutput = output
    .replace('</title>', '')
    .replace('</a>', '')
    .replace('</h1>', '')
    .replace('</pre>', '')
    .replace('</body>', '')
    .replace('</html>', '');

// Also try to optimize meta viewport if safe (but width=device-width requires quotes due to =)
// So we keep quotes there.

fs.writeFileSync('dist/index.html', finalOutput);

const stats = fs.statSync('dist/index.html');
console.log(`Original size: ${input.length} bytes`);
console.log(`Minified size: ${stats.size} bytes`);

if (stats.size > 1024) {
    console.error('ERROR: File size exceeds 1024 bytes!');
    process.exit(1);
}
